"""Constants for the Requestarr integration."""

DOMAIN = "requestarr"

DEFAULT_PORT = 8080
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_SECONDARY_SCAN_INTERVAL = 300
DEFAULT_TIMEOUT = 30

CONF_USE_SSL = "use_ssl"

FRONTEND_SCRIPT_URL = f"/{DOMAIN}/{DOMAIN}-card.js"
